DROP TABLE IF EXISTS noteful_folders;
DROP TABLE IF EXISTS noteful_notes;


CREATE TABLE noteful_folders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);


CREATE TABLE noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    folderId INTEGER REFERENCES noteful_folders(id), 
    content TEXT,
    modified TIMESTAMPTZ DEFAULT now() NOT NULL
);